<!DOCTYPE html>
<html>
    <title>PHP Examples</title>
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css" rel="stylesheet">
	<style>
		body {
			padding-top: 10px; /* 60px to make the container go all the way to the bottom of the topbar */
			font-family: "Segoe UI", Verdana, Helvetica, Sans;
		}
		h1 {
			font-size: 	24pt;
		}
		li { padding-bottom: 8pt;}
	</style>

<body>

	<div class="container">
    
		<div class="row-fluid">
			<div class="span12">	
			<h1>Unit 27: Web Server Scripting</h1>
            <h2>PHP Examples</h2>
			</div>
		</div>
	
	<div class="row-fluid">
        <div class="span3">
            <div class="well">
                This page is generated by a PHP file. It has a list of PHP examples.
            </div>
        </div>
        <div class="span9">
        
<?php
	// set the path on the server that we want to view files
	$d = dir("/Users/mrford/Sites/mrford.koding.com/website/unit27/examples");
	// print out some stats 
    
	echo "Path: " . $d->path . "<br>\n";
	
    echo "<p>Contents:</p>";
	// create an unorder list to hold the filenames
	echo "<ul>";
	// loop and keep reading from the path object 
	while (false !== ($entry = $d->read())) {
		/* 
			create a list item for each entry in the folder. Include an anchor so we can click to open that file */
		// QUESTION: for this to work where must the file me located relative to this PHP file?
		if($entry != "." && $entry != "..")
            echo "<li><a href='".$entry."'>".$entry."</a></li>\n";
	}
	echo "</ul>";

	// tidy up
	$d->close();
?>

            </div> <!-- /span 9 -->
        </div> <!-- /row-fluid -->
    </div> <!-- /container -->

</body>
</html>